name: tellesports
description: A new Flutter project.
version: 1.0.0+6
environment: 
  sdk: ">=2.17.0 <3.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.0
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  retry: ^3.1.2
  provider: ^6.1.1
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  uuid: ^4.3.3
  # flutterwave_standard: ^1.0.7
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_tawkto: ^0.0.3
  country_picker: ^2.0.25
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  swipe_to: ^1.0.2
  flutter_riverpod: ^2.4.10
  page_route_animator: ^1.0.3
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.8.1
  read_more_text: ^0.0.5
  flutter_image_compress: ^2.2.0
  url_launcher: ^6.2.5
dev_dependencies: 
  flutter_test: 
    sdk: flutter

  change_app_package_name: ^1.1.0  

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tella.png"    
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansBlack.ttf
          weight: 900
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansLight.ttf
          weight: 300
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
