name: tellesports
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2
  flutter_svg_provider: ^1.0.3
  intl: ^0.18.0
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  image_cropper: ^4.0.1
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  retry: ^3.1.2
  provider: ^6.1.1
  
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  sign_in_with_apple: ^5.0.0
  uuid: ^4.3.3
  flutterwave_standard: ^1.0.7
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_tawkto: ^0.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter

  change_app_package_name: ^1.1.0  

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"    
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansBlack.ttf
          weight: 900
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansLight.ttf
          weight: 300
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
