// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LgHPA0O3BJxASQTC--Tpo133XSSLOsc',
    appId: '1:126493581952:android:3d39708f600b020f3abc65',
    messagingSenderId: '126493581952',
    projectId: 'tellasport',
    storageBucket: 'tellasport.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5MGWcjPKKIU6IJweJGo38ZXydq9vqUE',
    appId: '1:126493581952:ios:f661eeeaa626ebc53abc65',
    messagingSenderId: '126493581952',
    projectId: 'tellasport',
    storageBucket: 'tellasport.appspot.com',
    androidClientId: '126493581952-6s0bb95on2j17ksksb2lgpnkts8rr35d.apps.googleusercontent.com',
    iosClientId: '126493581952-qgphq58u36tfnojmbqirffr54m5jum9o.apps.googleusercontent.com',
    iosBundleId: 'com.tellesports.tellesports',
  );
}
