import '../community_one_page/widgets/communitypagecomponent2_item_widget.dart';import 'package:flutter/material.dart';import 'package:tellesports/core/app_export.dart';import 'package:tellesports/widgets/custom_text_form_field.dart';class CommunityOnePage extends StatefulWidget {const CommunityOnePage({Key? key}) : super(key: key);

@override CommunityOnePageState createState() =>  CommunityOnePageState();

 }

// ignore_for_file: must_be_immutable
class CommunityOnePageState extends State<CommunityOnePage> with  AutomaticKeepAliveClientMixin<CommunityOnePage> {TextEditingController searchController = TextEditingController();

@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 12.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(children: [CustomTextFormField(controller: searchController, hintText: "Search for communities or users", hintStyle: CustomTextStyles.titleSmallGray400, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(20.h, 5.v, 9.h, 5.v), child: CustomImageView(imagePath: ImageConstant.imgSearchGray400, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 34.v), contentPadding: EdgeInsets.only(top: 7.v, right: 30.h, bottom: 7.v), borderDecoration: TextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray100), SizedBox(height: 22.v), SizedBox(height: 750.v, width: 350.h, child: Stack(alignment: Alignment.center, children: [_buildCommunityPageComponent1(context), _buildCommunityPageComponent2(context)])), _buildCommunityPageComponent3(context), _buildCommunityPageComponent4(context), _buildCommunityPageComponent3(context), _buildCommunityPageComponent4(context), _buildCommunityPageComponent3(context), _buildCommunityPageComponent4(context)]))]))))); } 
 
Widget _buildCommunityPageComponent1(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 75.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDisplayPicture, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h), margin: EdgeInsets.symmetric(vertical: 7.v)), Expanded(child: Container(margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.only(top: 9.v, bottom: 8.v), decoration: AppDecoration.outlineGray, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 12.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Joshua11", style: CustomTextStyles.titleMediumOnPrimary_1), SizedBox(height: 3.v), Text("Let’s choose the first option", style: CustomTextStyles.titleSmallGray600)])), Padding(padding: EdgeInsets.only(bottom: 36.v), child: Text("Sun", style: CustomTextStyles.titleSmallGray600))])))]))); } 
 
Widget _buildCommunityPageComponent2(BuildContext context) { return Align(alignment: Alignment.center, child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 9, itemBuilder: (context, index) {return Communitypagecomponent2ItemWidget(onTapCommunityPageComponent: () {onTapCommunityPageComponent(context);});})); } 
/// Common widget
Widget _buildCommunityPageComponent3(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDisplayPicture60x60, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h), margin: EdgeInsets.symmetric(vertical: 7.v)), Expanded(child: Container(margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.only(top: 7.v, bottom: 6.v), decoration: AppDecoration.outlineGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(children: [Text("Pixsellz Team", style: CustomTextStyles.titleMediumOnPrimary_1), SizedBox(height: 2.v), Text("Hasan Web", style: theme.textTheme.titleSmall), SizedBox(height: 2.v), Text("GIF", style: CustomTextStyles.titleSmallGray600)]), Padding(padding: EdgeInsets.only(left: 3.h, top: 3.v, bottom: 40.v), child: Text("12:23", textAlign: TextAlign.right, style: CustomTextStyles.titleSmallGray600))])))]); } 
/// Common widget
Widget _buildCommunityPageComponent4(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDisplayPicture, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h), margin: EdgeInsets.symmetric(vertical: 7.v)), Expanded(child: Container(margin: EdgeInsets.only(left: 10.h), padding: EdgeInsets.only(top: 10.v, bottom: 9.v), decoration: AppDecoration.outlineGray, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 14.v), child: Column(children: [Text("Joshua11", style: CustomTextStyles.titleMediumOnPrimary_1), SizedBox(height: 2.v), Text("Let’s choose the first option", style: CustomTextStyles.titleSmallGray600)])), Padding(padding: EdgeInsets.only(left: 3.h, bottom: 37.v), child: Text("Sun", textAlign: TextAlign.right, style: CustomTextStyles.titleSmallGray600))])))]); } 
/// Navigates to the communityChatEmptyStateScreen when the action is triggered.
onTapCommunityPageComponent(BuildContext context) { Navigator.pushNamed(context, AppRoutes.communityChatEmptyStateScreen); } 
 }
